import { hello } from './modules/_hello.js';
import {map} from "./modules/_map.js";
import { burger } from './modules/_burger.js';
import { initSlider } from "./modules/_initSlider.js";
import { animationScroll } from "./modules/_animationScroll.js";
import { scrollHeader } from "./modules/_scrollHeader.js";
import { pressDawn } from "./modules/_pressDawn.js";
import { pressUp } from "./modules/_pressUp.js";
import { sendForm } from "./modules/_form.js";
import {animationBcard} from "./modules/_animationBcard.js";
import {openDescriptCard} from "./modules/_openDescriptCard().js";

hello();
map();
burger();
initSlider();
animationScroll();
scrollHeader();
pressDawn();
pressUp();
sendForm();
animationBcard();
openDescriptCard();